const phrases = [
  "Look above",
  "Think outside",
  "Push and pull",
  "Think BIGGGGGG",
  "Map it and reduce it",
  "Give it a shake",
  "Shapes of pasta",
  "Organic design",
  "Simulated results",
  "Cats can jump real high",
  "Fold it like paper",
  "Gyroscopic motion",
  "Nanoparticles",
  "Squares, triangles, and octagons",
  "Flip it upside-down",
  "Rotate left for 2 seconds",
  "Twist",
  "Circuit board",
  "Cool it down then heat it up",
  "Form connections",
  "Break the mold",
  "Put the mold back together",
  "What happens if you drop it?",
  "Use it blindfolded",
  "Imagine a long crank to get it started",
  "What if it could talk?",
  "Ocean waves",
  "Stealth technology",
  "Ironman suit",
  "Cardboard",
  "Lasers, lasers, lasers",
  "Firing a cannon",
  "Ship in a bottle",
  "Shaving",
  "Wood carving",
  "3D printing ograns",
  "The next cyborg",
  "The Jettsons",
  "Building of the Pyramids",
  "Trade up",
  "Big brother",
  "Drifting",
  "Hydroplane",
  "Make it from primitives",
  "Draw with opposite hand",
  "Plug your brain into a computer",
  "Fly around for a bit",
  "What if you were the size of an ant?",
  "Let's go for a walk",
  "Circle, circle, dot, dot",
  "Keep it secret, keep it safe",
  "Drill",
  "Screw threads",
  "Diving board",
  "Compression spring",
  "Torsion spring",
  "Gearbox",
  "Casting",
  "Volcano erupting",
  "Pour molten metal",
  "Fix the point of view",
  "What is the point?",
  "Help the others",
  "Face the facts",
  "Prism",
  "Crystals in caves",
  "Explode",
  "Shatter the glass into fractals",
  "Imagine being the world's greatest mathematician",
  "Albert Einstein for a day",
  "Drop a key on the floor",
  "Build it and they will come",
  "Everything the light touches",
  "See through the dark",
  "Potter shaping the clay",
  "Feel with your mind",
  "Make it harder",
  "Make it softer",
  "It feels really cold",
  "Tesla coil",
  "Tank tracks",
  "Deer footprints",
  "Put the shapes into the holes in the box",
  "What if it were stretchy?",
  "Don't let it snap",
  "Throw it against the wall",
  "There's beauty in imperfection",
  "1-step, 2-step, 3-step, 4",
  "Stages of its life",
  "You love working with it",
  "It's beautiful",
  "Make it impossible",
  "Make it dissolve",
  "Ant colonies",
  "Satellites",
]

module.exports = {
  phrases,
}